var incomingWidget = {
	'id' : 1,
    'title' : 'Widget with auto text compression/height',
	'type' : 'text',
	'value' : 'Text',
	'bold' : false,
	'italic' : false,
	'underline' : true,
	'align-x' : 'c',
	'align-y' : 'm',
	'text-x-compression-mode' : true,
	'text-x-compression-min' : 0.4,
	'text-x-compression-default' : 0.95,
	'text-x-compression-step' : 0.01,
	'text-height-calculate-mode' : true,
	'text-height' : 40,
	'text-height-step' : 1,
	'text-height-min' : 40,
	'text-height-max' : 80,
	'text-height-dimension' : 'pt',
    'block-height-max' : 100,
    'block-width-max' : 450,
    'block-height-min' : 50,
    'block-width-min' : 200,
	'block-height' : 100,
	'block-width' : 200,
    'block-size-dimension' : 'px',
    'block-x-position' : 20,
    'block-y-position' : 20,
    'block-position-dimension' : 'px'
};
var incomingWidget2 = {
    'id' : 2,
    'title' : 'Widget with incompressible text',
    'type' : 'text',
    'value' : 'Custom user text',
    'bold' : false,
    'italic' : false,
    'underline' : false,
    'align-x' : 'l',
    'align-y' : 'm',
    'text-x-compression-mode' : false,
    'text-x-compression-min' : 1,
    'text-x-compression-default' : 1,
    'text-x-compression-step' : 0.01,
    'text-height-calculate-mode' : false,
    'text-height' : 40,
    'text-height-step' : 1,
    'text-height-min' : 80,
    'text-height-max' : 80,
    'text-height-dimension' : 'pt',
    'block-height-max' : 100,
    'block-width-max' : 450,
    'block-height-min' : 50,
    'block-width-min' : 200,
    'block-height' : 100,
    'block-width' : 450,
    'block-size-dimension' : 'px',
    'block-x-position' : 10,
    'block-y-position' : 250,
    'block-position-dimension' : 'px'
};
var incomingArtWidget = {
	'id' : 150,
	'type' : 'art',
	'width' : 100,
	'height' : 100,
	'demension' : 'px',
	'value' : null,
	'default-value' : ''
};
var incomingTemplate = {
	'id' : 1,
	'type' : 'floor_sign',
	'color_scheme' : 'black'
};